### ISSUE TITLE
Library submission.

### ISSUE THREAD

**Issue by chrisjldoran** [MonumoLtd/SimpleGA.jl#13]
@tpgillam 
Tom,

Just resubmitted the SimpleGA library, and made contact with people at JuliaCon to make sure it passes submission this time. No-one is worried about the name conflict. 

But if you look at the PR:
https://github.com/JuliaRegistries/General/pull/88562
Is there an issue with it failing tests? It seems to have failed some, but I don't know if they are critical.

**Comment by tpgillam** [comment]
Sorry, not sure how I missed this — seems like it's all good now though!
